apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Text-adventure
  annotations:
    github.com/project-slug: codeiain/Text-adventure
spec:
  type: other
  lifecycle: unknown
  owner: guests
